extends Node


var script_voice = {
	"Yikes, I need to be more careful!": "res://assets/audio/dr_sarah_script_audio/be_more_careful.mp3",
	"I don’t think that will work.": "res://assets/audio/dr_sarah_script_audio/don_think_work.mp3",
	"I can’t do that.":"res://assets/audio/dr_sarah_script_audio/cant_do_that.mp3",
	"I already have it.": "res://assets/audio/dr_sarah_script_audio/already_have_it.mp3",
	"I need to get it first.": "res://assets/audio/dr_sarah_script_audio/need_get_first.mp3",
	"It's amazing that this apple looks so fresh.": "res://assets/audio/dr_sarah_script_audio/apple_looks_fresh.mp3",
	"This must be Rakush. I wonder what he wants with this village?":"res://assets/audio/dr_sarah_script_audio/must_be_rakush.mp3",
	"I must find a way to get Rakush to leave.": "res://assets/audio/dr_sarah_script_audio/get_rakush_leave.mp3",
	"The village elder is not here.": "res://assets/audio/dr_sarah_script_audio/village_elder_not_here.mp3",
	"It’s a beautiful blue crystal.":"res://assets/audio/dr_sarah_script_audio/look_crystal_blue.mp3",
	"This is a marvellous green crystal.":"res://assets/audio/dr_sarah_script_audio/look_crystal_green.mp3",
	"A fantastic yellow crystal.":"res://assets/audio/dr_sarah_script_audio/look_crystal_yellow.mp3",
	"An incredible red crystal.":"res://assets/audio/dr_sarah_script_audio/look_crystal_red.mp3",
	"I need to use it ON something.":"res://assets/audio/dr_sarah_script_audio/need_use_on.mp3",
	"A weak wall. I think I could break this with something.":"res://assets/audio/dr_sarah_script_audio/weak_wall_could_break.mp3",
	"I need to get closer.":"res://assets/audio/dr_sarah_script_audio/get_closer.mp3",
	"I think there must be a button somewhere.":"res://assets/audio/dr_sarah_script_audio/must_be_button.mp3",
	"That's not going to open it.":"res://assets/audio/dr_sarah_script_audio/not_going_to_open_it.mp3",
	"This door does not open with a key.":"res://assets/audio/dr_sarah_script_audio/not_open_key.mp3",
	"The door is closed.":"res://assets/audio/dr_sarah_script_audio/door_closed.mp3",
	"The door is open.": "res://assets/audio/dr_sarah_script_audio/door_open.mp3",
	"The door is locked.": "res://assets/audio/dr_sarah_script_audio/door_locked.mp3",
	"A wooden crate. I can see an apple inside.":"res://assets/audio/dr_sarah_script_audio/look_crate.mp3",
	"Maybe I can break it open?":"res://assets/audio/dr_sarah_script_audio/maybe_break_open.mp3",
	" I cannot get this.": "res://assets/audio/dr_sarah_script_audio/cant_get.mp3",
	"It says the alpha key.":"res://assets/audio/dr_sarah_script_audio/key_alpha.mp3",
	"It says the beta key.":"res://assets/audio/dr_sarah_script_audio/key_beta.mp3",
	"It says the delta key.":"res://assets/audio/dr_sarah_script_audio/key_delta.mp3",
	"It says the alpha door.":"res://assets/audio/dr_sarah_script_audio/door_alpha.mp3",
	"It says the beta door.":"res://assets/audio/dr_sarah_script_audio/door_beta.mp3",
	"It says the delta door.":"res://assets/audio/dr_sarah_script_audio/door_delta.mp3",
	"The fuse box is off. It needs a fuse.":"res://assets/audio/dr_sarah_script_audio/fuse_box_off.mp3",
	"The fuse box is on.":"res://assets/audio/dr_sarah_script_audio/fuse_box_on.mp3",
	"That's not going to open it. It needs a key.":"res://assets/audio/dr_sarah_script_audio/not_open_key.mp3",
	"It's open. It just needs a fuse.":"res://assets/audio/dr_sarah_script_audio/open_just_need_fuse.mp3",
	"It needs a fuse.":"res://assets/audio/dr_sarah_script_audio/needs_fuse.mp3",
	"I cannot pick up fire!":"res://assets/audio/dr_sarah_script_audio/cant_get_fire.mp3",
	"It is too hot to walk past.":"res://assets/audio/dr_sarah_script_audio/too_hot_walk_past.mp3",
	"I can't do that with fire!":"res://assets/audio/dr_sarah_script_audio/cant_do_fire.mp3",
	"I put on the coat.":"res://assets/audio/dr_sarah_script_audio/coat_on.mp3",
	"I put on the skates.":"res://assets/audio/dr_sarah_script_audio/skates_on.mp3",
	"I put on the mask.": "res://assets/audio/dr_sarah_script_audio/mask_on.mp3",
	"I put on the gloves.":"res://assets/audio/dr_sarah_script_audio/gloves_on.mp3",
	"I am not wearing the coat.":"res://assets/audio/dr_sarah_script_audio/not_wearing_coat.mp3",
	"I am not wearing the mask.":"res://assets/audio/dr_sarah_script_audio/not_wearing_mask.mp3",
	"I am not wearing the gloves.":"res://assets/audio/dr_sarah_script_audio/not_wearing_gloves.mp3",
	"I am not wearing the skates.":"res://assets/audio/dr_sarah_script_audio/not_wearing_skates.mp3",
	"I am already wearing the mask.":"res://assets/audio/dr_sarah_script_audio/already_wearing_mask.mp3",
	"I am already wearing the coat.":"res://assets/audio/dr_sarah_script_audio/already_wearing_coat.mp3",
	"I am already wearing the skates.": "res://assets/audio/dr_sarah_script_audio/already_wearing_skates.mp3",
	"I am already wearing the gloves.":"res://assets/audio/dr_sarah_script_audio/already_wearing_gloves.mp3",
	"A fireproof coat. I can walk through fire wearing this.":"res://assets/audio/dr_sarah_script_audio/fireproof_coat.mp3",
	"Roller skates. These will help me move quickly.":"res://assets/audio/dr_sarah_script_audio/roller_skates.mp3",
	"A diving mask. I can swim underwater with this.":"res://assets/audio/dr_sarah_script_audio/diving_mask.mp3",
	"Climbing gloves. I can climb some walls with these.":"res://assets/audio/dr_sarah_script_audio/climbing_gloves.mp3",
	"I need this for the children.":"res://assets/audio/dr_sarah_script_audio/need_for_children.mp3",
	"This is the medicine to treat TB. There is enough for the whole village.":"res://assets/audio/dr_sarah_script_audio/medicine_for_tb.mp3",
	"I should give the medicine to the boy now.":"res://assets/audio/dr_sarah_script_audio/give_medicine_boy.mp3",
	"I should give the medicine to the girl now.":"res://assets/audio/dr_sarah_script_audio/give_medicine_girl.mp3",
	"Take this medicine. It should help you get well.":"res://assets/audio/dr_sarah_script_audio/take_medicine.mp3",
	"I need to ask permission from a parent first.": "res://assets/audio/dr_sarah_script_audio/ask_permission.mp3",
	"Take this. It will help you to feel better.":"res://assets/audio/dr_sarah_script_audio/take_feel_better.mp3",
	"The boy has already taken his medicine.":"res://assets/audio/dr_sarah_script_audio/boy_has_taken.mp3",
	"The girl has already taken her medicine.":"res://assets/audio/dr_sarah_script_audio/girl_has_taken.mp3",
	"The boy is really unwell.":"res://assets/audio/dr_sarah_script_audio/boy_unwell.mp3",
	"The girl looks really sick.":"res://assets/audio/dr_sarah_script_audio/girl_sick.mp3",
	"A long ladder. This will be useful.":"res://assets/audio/dr_sarah_script_audio/long_ladder.mp3",
	"A very long rope. This will help me a lot.":"res://assets/audio/dr_sarah_script_audio/very_long_rope.mp3",
	"It seems to be broken.":"res://assets/audio/dr_sarah_script_audio/seems_broken.mp3",
	"The lever is already on. Try pulling it.":"res://assets/audio/dr_sarah_script_audio/lever_is_on.mp3",
	"The lever is already off. Try pushing it.":"res://assets/audio/dr_sarah_script_audio/lever_is_off.mp3",
	"I cannot pick up a log!":"res://assets/audio/dr_sarah_script_audio/cant_get_log.mp3",
	"I think there must be a lever to move the log.":"res://assets/audio/dr_sarah_script_audio/lever_move_log.mp3",
	"A large log. Useful for walking over.":"res://assets/audio/dr_sarah_script_audio/large_log_useful.mp3",
	"Nothing happened. I think it needs power.":"res://assets/audio/dr_sarah_script_audio/nothing_happened_needs_power.mp3",
	"The button is on.":"res://assets/audio/dr_sarah_script_audio/button_on.mp3",
	"The button is off.":"res://assets/audio/dr_sarah_script_audio/button_off.mp3",
	"I think I need to push this button.":"res://assets/audio/dr_sarah_script_audio/need_push_button.mp3",
	"She looks really worried about her children.":"res://assets/audio/dr_sarah_script_audio/she_looks_worried.mp3",
	"I can't take the woman.": "res://assets/audio/dr_sarah_script_audio/cant_take_woman.mp3",
	"I can't do that with her.": "res://assets/audio/dr_sarah_script_audio/cant_do_with_her.mp3",
	"Click on the girl.":"res://assets/audio/narrator_audio_script/click_one_girl.mp3",
	"Click on the boy.":"res://assets/audio/narrator_audio_script/click_one_on_boy.mp3",
	"Click again on the boy.":"res://assets/audio/narrator_audio_script/click_again_boy.mp3",
	"Click again on the girl.":"res://assets/audio/narrator_audio_script/click_again_girl.mp3",
	"Click again on the lever.":"res://assets/audio/narrator_audio_script/click_again_lever.mp3",
	"Click on the lever.":"res://assets/audio/narrator_audio_script/click_on_the_lever.mp3",
	"Go through the door.":"res://assets/audio/narrator_audio_script/go_through_door.mp3",
	"Click on the medicine box to get it.":"res://assets/audio/narrator_audio_script/click_med_box_to_get.mp3",
	"Press the RIGHT arrow key to walk.": "res://assets/audio/narrator_audio_script/right_arrow.mp3",
	"Press UP to jump.": "res://assets/audio/narrator_audio_script/up_jump.mp3",
	"Follow the arrow. Click on the word Get.":"res://assets/audio/narrator_audio_script/follow_arrow_click_get.mp3",
	"Give the medicine to the boy. Follow the arrow.": "res://assets/audio/narrator_audio_script/give_medicine_boy.mp3",
	"I think I can climb that rope.": "res://assets/audio/dr_sarah_script_audio/can_climb_rope.mp3",
	"I can climb this ladder and take it with me.":"res://assets/audio/dr_sarah_script_audio/climb_ladder_take.mp3",
	"Press the UP arrow key to climb the rope.":"res://assets/audio/narrator_audio_script/press_up_climb_rope.mp3",
	"Press the UP arrow key to go trough the door.":"res://assets/audio/narrator_audio_script/press_up_door.mp3",
	"I need to get out of this cave.": "res://assets/audio/dr_sarah_script_audio/need_get_out_cave.mp3",
	"I need to get out of here and back to the village.":"res://assets/audio/dr_sarah_script_audio/need_back_village.mp3",
	"I think I need an object that solves this riddle.":"res://assets/audio/dr_sarah_script_audio/need_solve_riddle.mp3",
	"I was hoping that was the exit, guess I’d better keep going.":"res://assets/audio/dr_sarah_script_audio/was_hoping_exit.mp3",
	"My hands will help you stay organised.": "res://assets/audio/riddles/clock_hands.mp3",
	"I need to put an item in this hole.":"res://assets/audio/dr_sarah_script_audio/put_item_hole.mp3",
	"I need to put the correct item here.":"res://assets/audio/dr_sarah_script_audio/correct_item_here.mp3",
	"I cannot get that.":"res://assets/audio/dr_sarah_script_audio/cannot_get_that.mp3",
	"There’s something written on that sign. I should look at it.":"res://assets/audio/dr_sarah_script_audio/something_written_sign.mp3",
	"Looks like I need to find an item that solves this riddle.":"res://assets/audio/dr_sarah_script_audio/find_item_solve_riddle.mp3",
	"A clock has hands and keeps you organised. I should take this to that hole by the sign.":"res://assets/audio/dr_sarah_script_audio/clock_take_hole.mp3",
	"Wow! That opened the door. I wonder how that works?":"res://assets/audio/dr_sarah_script_audio/wow_opened_door.mp3",
	"Click again on the sign. Remember to click two times to complete your sentence.":"res://assets/audio/narrator_audio_script/click_again_sign.mp3",
	"Click again on the hole. Remember to click two times to complete your sentence.": "res://assets/audio/narrator_audio_script/click_again_hole.mp3",
	"Click again on the clock.  Remember to click two times to complete your sentence.":"res://assets/audio/narrator_audio_script/click_again_clock.mp3",
	"Nothing happened. That must be the wrong item.":"res://assets/audio/dr_sarah_script_audio/nothing_happened.mp3",
	"I should try putting this clock in the hole.":"res://assets/audio/dr_sarah_script_audio/try_put_clock_hole.mp3",
	"Some of my items vanished!":"res://assets/audio/dr_sarah_script_audio/some_items_vanished.mp3",
	"The mirror I was carrying has vanished. It must be some kind of magic item.":"res://assets/audio/dr_sarah_script_audio/mirror_vanished_magic.mp3",
	"Wow. This looks expensive. I should find someone to give it to.":"res://assets/audio/dr_sarah_script_audio/wow_expensive_give_it.mp3",
	"Maybe I should look at this sign for a clue.":"res://assets/audio/dr_sarah_script_audio/look_sign_clue.mp3",
	"It feels like I am never going to get out of here.":"res://assets/audio/dr_sarah_script_audio/feels_like_never_out.mp3",
	"There must we a way back to the surface. I think I just need to keep moving up.":"res://assets/audio/dr_sarah_script_audio/way_back_move_up.mp3",
	"There is something in the hole already. I need to remove it first.":"res://assets/audio/dr_sarah_script_audio/shelf_already_remove_item.mp3",
	"Click 2 times on the mirror to take it back.":"res://assets/audio/narrator_audio_script/click_mirror_get_back.mp3",
	"I hold your twin inside.":"res://assets/audio/riddles/mirror_twin.mp3",
	"I need to read the sign and find an object that answers the riddle. When I find the object, I need to put it in the hole.":"res://assets/audio/dr_sarah_script_audio/help.mp3",
	"Now give some medicine to the girl.":"res://assets/audio/narrator_audio_script/now_give_med_girl.mp3",
	"Click on Push.":"res://assets/audio/narrator_audio_script/click_push.mp3",
	"I need to be quick.":"res://assets/audio/dr_sarah_script_audio/need_be_quick.mp3",
	"Looks like I am going to have to swim.":"res://assets/audio/dr_sarah_script_audio/have_to_swim.mp3",
	"I should go back and get the ladder.":"res://assets/audio/dr_sarah_script_audio/go_back_get_ladder.mp3",
	"I can use the ladder and put it here. Click on 'Use' and then click on the ladder.":"res://assets/audio/dr_sarah_script_audio/use_ladder_single_click.mp3",
	"The bell I was carrying has vanished. It must be some kind of magic item.":"res://assets/audio/dr_sarah_script_audio/bell_vanished.mp3",
	"It’s a ladder.":"res://assets/audio/dr_sarah_script_audio/its_ladder.mp3",
	"It’s a bell.":"res://assets/audio/dr_sarah_script_audio/its_bell.mp3",
	"It’s a mirror.":"res://assets/audio/dr_sarah_script_audio/its_mirror.mp3",
	"I should remember to look at that sign above the hole for a clue.":"res://assets/audio/dr_sarah_script_audio/remind_look_sign.mp3",
	"My name is Dr. Sarah Bari":"res://assets/audio/dr_sarah_script_audio/my_name_sarah.mp3",
	"My favourite colour is purple.":"res://assets/audio/dr_sarah_script_audio/fav_colour.mp3",
	"I am 27 years old.":"res://assets/audio/dr_sarah_script_audio/i_am_27.mp3",
	"I should GET this ladder.":"res://assets/audio/dr_sarah_script_audio/should_get_this_ladder.mp3",
	"With me, you can create worlds.":"res://assets/audio/riddles/pen_create_worlds.mp3",
	"To get the ladder click 'Get' and then click on the ladder.":"res://assets/audio/narrator_audio_script/get_ladder_single.mp3",
	"If you cannot see the ladder, you can click 'Get' followed by the ladder icon in the inventory…":"res://assets/audio/narrator_audio_script/get_ladder_inventory_icon_single.mp3",
	"...it will come back to you. Maybe it’s magic.":"res://assets/audio/narrator_audio_script/it_come_back_maybe_magic.mp3",
	"The telescope I was carrying has vanished. It must be some kind of magic item.":"res://assets/audio/telescope_vanished_magic.mp3",
	"There is something in the hole already, I need to remove it first.":"res://assets/audio/dr_sarah_script_audio/something_hole_already.mp3",
	"I can't do that with it.":"res://assets/audio/dr_sarah_script_audio/cant_do_that_with_it.mp3",
	"I need to use it 'IN' something.":"res://assets/audio/dr_sarah_script_audio/need_use_in_something.mp3",
	"Play this level to create your story.":"res://assets/audio/dr_sarah_script_audio/play_level_create_story.mp3",
	"Place the ladder and click to drop it.":"res://assets/audio/narrator_audio_script/place_ladder.mp3",
	"I wonder if I should push the red button?":"res://assets/audio/dr_sarah_script_audio/wonder_should_push_btn.mp3",
	"Yes! You can write stories and create your own worlds with a pen!":"res://assets/audio/dr_sarah_script_audio/riddle_solves/yes_pen.mp3",
	"Oh! When I look in the mirror, I see my twin!":"res://assets/audio/dr_sarah_script_audio/riddle_solves/mirro_see_twin.mp3",
	"I think I could break this with something.":"res://assets/audio/dr_sarah_script_audio/i_think_could_break.mp3",
	"A strong hammer":"res://assets/audio/dr_sarah_script_audio/strong_hammer.mp3",
	"There must be a button to move this log.": "res://assets/audio/dr_sarah_script_audio/button_to_move_log.mp3",
	"Text entry mode.":"res://assets/audio/narrator_audio_script/text_entry_mode.mp3",
	"Click mode.":"res://assets/audio/narrator_audio_script/click_mode.mp3",
	"Click again. Remember to click two times to complete your sentence.":"res://assets/audio/narrator_audio_script/click_again_complete_sentence.mp3",
	"My voice can be a warning.":"res://assets/audio/riddles/bell_voice.mp3",
	"Yes, the sound of a bell can be a warning!":"res://assets/audio/dr_sarah_script_audio/yes_sound_of_bell_warning.mp3",
	"The pen I was carrying has vanished. It must be some kind of magic item.":"res://assets/audio/dr_sarah_script_audio/pen_has_vanished.mp3",
	"It's a hammer.":"res://assets/audio/dr_sarah_script_audio/its_hammer.mp3",
	"It's a pen.":"res://assets/audio/dr_sarah_script_audio/its_pen.mp3",
	"It's a yellow crystal.":"res://assets/audio/dr_sarah_script_audio/its_yellow_crystal.mp3",
	"It's a telescope.":"res://assets/audio/dr_sarah_script_audio/its_telescope.mp3",
	"It's a compass.":"res://assets/audio/dr_sarah_script_audio/its_compass.mp3",
	"It's a boomerang.":"res://assets/audio/dr_sarah_script_audio/its_boomerang.mp3",
	"I will always come back to you.":"res://assets/audio/riddles/boomerang_come_back.mp3",
	"I can show you the way when you are lost.":"res://assets/audio/riddles/compass_show_way.mp3",
	"The compass I was carrying has vanished.":"res://assets/audio/dr_sarah_script_audio/compass_has_vanished.mp3",
	"The boomerang I was carrying has vanished.":"res://assets/audio/dr_sarah_script_audio/boomerang_has_vanished.mp3",
	"Of course, a boomerang comes back to you when you throw it.":"res://assets/audio/dr_sarah_script_audio/boomerang_comes_back_when_throw.mp3",
	"For a lift, type Orville.":"res://assets/audio/secrets/orville.mp3",
	"Save the hammer; type open sesame.":"res://assets/audio/secrets/open_sesame.mp3",
	"In a hurry? Type Jay Garrick.":"res://assets/audio/secrets/jay_garrick.mp3",
	"I can't do that with the rock.":"res://assets/audio/dr_sarah_script_audio/cant_do_with-rock.mp3",
	"Relax, TYPE dance": "res://assets/audio/secrets/dance.mp3",
	"For a different view, type Escher":"res://assets/audio/secrets/escher.mp3",
	"To go back TYPE XYZZY":"res://assets/audio/secrets/xyzzy.mp3",
	"To see the sign again, type Berg":"res://assets/audio/secrets/berg_see_sign.mp3",
	"For more bounce, type pogo":"res://assets/audio/secrets/pogo_bounce.mp3",
	"I need to find something to put out this fire.":"res://assets/audio/dr_sarah_script_audio/put_out_fire.mp3",
	"I can show you the moon in the blink of an eye.":"res://assets/audio/riddles/telescope_moon.mp3",
	"The umbrella I was carrying has vanished.":"res://assets/audio/dr_sarah_script_audio/umbrella_vanished.mp3",
	"It's a glass of water.":"res://assets/audio/dr_sarah_script_audio/its_glass_water.mp3",
	"Yes! A telescope can show you a close up view of the moon.":"res://assets/audio/dr_sarah_script_audio/riddle_solves/yes_telescope_close_moon.mp3",
	"I keep your most precious things safe.":"res://assets/audio/riddles/padlock_precious.mp3",
	"My warm belly takes away your hunger.":"res://assets/audio/riddles/pot_warm_belly.mp3",
	"Yes! The cooking pot can take away my hunger.":"res://assets/audio/dr_sarah_script_audio/riddle_solves/yes_cooking_pot.mp3",
	"The lamp I was carrying has vanished.":"res://assets/audio/dr_sarah_script_audio/lamp_vanished.mp3",
	"I can help you see clearly.":"res://assets/audio/riddles/see_clearly.mp3",
	"Yes! Glasses can help you see clearly.":"res://assets/audio/dr_sarah_script_audio/riddle_solves/yes_glasses.mp3",
	"The telescope I was carrying has vanished.":"res://assets/audio/dr_sarah_script_audio/telescope_vanished.mp3",
	"It’s a diving mask. I can use this to swim underwater.":"res://assets/audio/dr_sarah_script_audio/diving_mask_swim_underwater.mp3",
	"I can use the diving mask to swim underwater.":"res://assets/audio/dr_sarah_script_audio/mask_reminder.mp3",
	"I put on the diving mask.":"res://assets/audio/dr_sarah_script_audio/put_on_mask.mp3",
	"I took off the diving mask.":"res://assets/audio/dr_sarah_script_audio/took_off_mask.mp3",
	"I can't take off the mask while I am diving.":"res://assets/audio/dr_sarah_script_audio/cant_mask_off_diving.mp3",
	"It’s a pair of glasses.":"res://assets/audio/dr_sarah_script_audio/its_glasses.mp3",
	"Get the rope and use it to climb.":"res://assets/audio/narrator_audio_script/get_rope.mp3",
	"I chase away the darkness.":"res://assets/audio/riddles/lamp_chase_darkness.mp3",
	"I sacrifice myself so you stay dry.":"res://assets/audio/riddles/umbrella_sacrifice.mp3",
	"Yes! An umbrella gets wet so I can stay dry.":"res://assets/audio/dr_sarah_script_audio/yes_umbrella_solution.mp3",
	"The pot I was carrying has vanished.":"res://assets/audio/dr_sarah_script_audio/pot_vanished.mp3"

#	"I am already wearing the diving mask":"res://assets/audio/dr_sarah_script_audio/already_wearing_mask.mp3",
	
}
