extends TextureButton

var is_inventory_item:= false

export var object_text := "the forcefield"

var the_player: KinematicBody2D

var is_on_shelf := false

var is_active = true

var state := "off"

onready var field_body = $"%solid_body"

func _ready():
	connect("pressed", self, "_on_pressed")
	GlobalSignals.connect("sentence_checker", self, "_sentence_check")
#	connect("mouse_entered", self, "_on_entered")
#	connect("mouse_exited", self, "_on_exit")
	GlobalSignals.connect("item_placed_on_shelf", self, "_placed_on_shelf")
	GlobalSignals.connect("padlock_opened", self, "_remove_me")
	GlobalSignals.connect("remove_forcefield", self, "_check_can_remove")
	set_state("off")

	
func set_state(new_state):
	state = new_state
	if state == "off":
		call_deferred("set_body", true)
		visible = false
	else:
		call_deferred("set_body", false)
		visible = true

func set_body(state):
	field_body.disabled = state

func _on_pressed():
	if GlobalVars.last_clicked == object_text:
		GlobalSignals.emit_signal("object_button_pressed")
	else:
		GlobalVars.last_clicked = object_text
		if object_text in GlobalVars.current_sentence:
			return
		if is_inventory_item and "Use" in GlobalVars.current_sentence and GlobalVars.current_sentence.length():
			GlobalSignals.emit_signal("update_on_hover", object_text, " on")
	#			GlobalSignals.emit_signal("add_with_preposition","on")
			GlobalVars.using_preposition = true
		else:
			GlobalSignals.emit_signal("update_on_hover", object_text)

#
#func _on_entered():
#	if object_text in GlobalVars.current_sentence:
#		return
#	if is_inventory_item and "Use" in GlobalVars.current_sentence and GlobalVars.current_sentence.length() < 5:
#		GlobalSignals.emit_signal("update_on_hover", object_text)
#		GlobalSignals.emit_signal("add_with_preposition","on")
#		GlobalVars.using_preposition = true
#	else:
#		GlobalSignals.emit_signal("update_on_hover", object_text)
#
#func _on_exit():
#	if GlobalVars.last_added == " on":
#		return
#	GlobalSignals.emit_signal("remove_object")

func _sentence_check(sentence):
	sentence = sentence.to_lower().strip_edges(true, true)
	var get := "get "+object_text
	var look := "look at "+object_text
	var open:= "open " + object_text
	var use := "use "+object_text
	var use_on := "use "+object_text+" on"	
	var on_shelf := "use "+object_text+" on the shelf"
	if not object_text in sentence:
		return
	match sentence:
		get:
			GlobalSignals.emit_signal("speak", "I cannot get the forcefield.")
		use:
			GlobalSignals.emit_signal("speak", "I can't use it.")

		use_on:
			return
		"use the hammer on the forcefield":
			GlobalSignals.emit_signal("speak", "That has no effect.")
		look:
			GlobalSignals.emit_signal("speak", "The forcefield is being generated by that man. No living creature can pass through it.")
		_:
			GlobalSignals.emit_signal("speak", "I can't do that with "+object_text)



func _get_closer():
	GlobalSignals.emit_signal("speak", "I need to get closer.")

func _check_can_remove():
	GlobalSignals.emit_signal("remove_from_game_objects", object_text)
	GlobalSignals.emit_signal("sentence_clear")	
	queue_free()

func _placed_on_shelf(the_item):
	if the_item == object_text:
		if !is_on_shelf:
			GlobalSignals.emit_signal("remove_from_game_objects", object_text)
			queue_free()

func _remove_me():
	GlobalSignals.emit_signal("remove_from_game_objects", object_text)
	queue_free()
